service: poc-proj-familyst

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1


functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get

          
